//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAdoNet01
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUsers
    {
        public string id { get; set; }
        public string nombre { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
    }
}
